/*
1.Valid rectangle: https://www.interviewbit.com/problems...
2.Bishop moves: https://www.interviewbit.com/problems..
3.Zero in Factorial: https://practice.geeksforgeeks.org/pr...
4.Nim Game: https://leetcode.com/problems/nim-gam...
*/